In [4]:
import pandas as pd

df = pd.read_csv(r"dataset\balanced_dataset_50_50.csv")

df

,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud
0,TRANSFER,129526.58,C1786736565,0.00,0.00,C1189777296,2103690.88,2233217.46,0.0
1,CASH_IN,304210.97,C2138211913,6638620.67,6942831.64,C1766776273,513871.60,209660.63,0.0
2,CASH_OUT,57905.63,C393598530,188.00,0.00,C769319919,611506.02,669411.65,0.0
3,CASH_IN,83102.70,C807731926,2274365.81,2357468.51,C322340400,122204.31,39101.61,0.0
4,PAYMENT,14341.19,C603392505,459181.00,444839.81,M1570710058,0.00,0.00,0.0
...,...,...,...,...,...,...,...,...,...
5065,CASH_OUT,82869.09,C1143635966,82869.09,0.00,C275663782,104258.05,187127.14,1.0
5066,TRANSFER,9960382.40,C427148786,9960382.40,0.00,C1532977706,0.00,0.00,1.0
5067,CASH_OUT,9960382.40,C1041938819,9960382.40,0.00,C1108421533,95048.58,10055430.98,1.0
5068,TRANSFER,1231309.64,C2120061745,1231309.64,0.00,C287066549,0.00,0.00,1.0
5069,CASH_OUT,1231309.64,C488263608,1231309.64,0.00,C168611895,27650.97,1258960.61,1.0

In [5]:
df.shape

(5070, 9)

In [6]:
df = df.drop(["nameOrig","nameDest"],axis=1)
df

,type,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud
0,TRANSFER,129526.58,0.00,0.00,2103690.88,2233217.46,0.0
1,CASH_IN,304210.97,6638620.67,6942831.64,513871.60,209660.63,0.0
2,CASH_OUT,57905.63,188.00,0.00,611506.02,669411.65,0.0
3,CASH_IN,83102.70,2274365.81,2357468.51,122204.31,39101.61,0.0
4,PAYMENT,14341.19,459181.00,444839.81,0.00,0.00,0.0
...,...,...,...,...,...,...,...
5065,CASH_OUT,82869.09,82869.09,0.00,104258.05,187127.14,1.0
5066,TRANSFER,9960382.40,9960382.40,0.00,0.00,0.00,1.0
5067,CASH_OUT,9960382.40,9960382.40,0.00,95048.58,10055430.98,1.0
5068,TRANSFER,1231309.64,1231309.64,0.00,0.00,0.00,1.0
5069,CASH_OUT,1231309.64,1231309.64,0.00,27650.97,1258960.61,1.0

In [7]:
df["isFraud"].value_counts()

isFraud
0.0    2535
1.0    2535
Name: count, dtype: int64

In [8]:
df.columns

Index(['type', 'amount', 'oldbalanceOrg', 'newbalanceOrig', 'oldbalanceDest',
       'newbalanceDest', 'isFraud'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5070 entries, 0 to 5069
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   type            5070 non-null   object
 1   amount          5070 non-null   float64
 2   oldbalanceOrg   5070 non-null   float64
 3   newbalanceOrig  5070 non-null   float64
 4   oldbalanceDest  5070 non-null   float64
 5   newbalanceDest  5070 non-null   float64
 6   isFraud         5070 non-null   float64
dtypes: float64(6), object(1)
memory usage: 277.4+ KB

In [10]:
df.describe()

,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud
count,5.070000e+03,5.070000e+03,5.070000e+03,5.070000e+03,5.070000e+03,5070.000000
mean,7.305437e+05,1.087883e+06,4.523101e+05,7.786253e+05,1.165501e+06,0.500000
std,1.605670e+06,2.672994e+06,2.136752e+06,2.252226e+06,2.612199e+06,0.500049
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000
25%,3.361776e+04,1.011947e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000
50%,1.677155e+05,1.133390e+05,0.000000e+00,0.000000e+00,1.438789e+05,0.500000
75%,5.223438e+05,7.980074e+05,0.000000e+00,5.533556e+05,1.152234e+06,1.000000
max,1.000000e+07,3.767004e+07,3.636535e+07,3.296166e+07,3.464570e+07,1.000000

In [11]:
df = pd.get_dummies(df,columns=['type'])
df.head()

,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud,type_CASH_IN,type_CASH_OUT,type_DEBIT,type_PAYMENT,type_TRANSFER
0,129526.58,0.00,0.00,2103690.88,2233217.46,0.0,False,False,False,False,True
1,304210.97,6638620.67,6942831.64,513871.60,209660.63,0.0,True,False,False,False,False
2,57905.63,188.00,0.00,611506.02,669411.65,0.0,False,True,False,False,False
3,83102.70,2274365.81,2357468.51,122204.31,39101.61,0.0,True,False,False,False,False
4,14341.19,459181.00,444839.81,0.00,0.00,0.0,False,False,False,True,False

In [12]:
df.columns

Index(['amount', 'oldbalanceOrg', 'newbalanceOrig', 'oldbalanceDest',
       'newbalanceDest', 'isFraud', 'type_CASH_IN', 'type_CASH_OUT',
       'type_DEBIT', 'type_PAYMENT', 'type_TRANSFER'],
      dtype='object')

In [13]:
col = ['type_CASH_IN', 'type_CASH_OUT','type_DEBIT', 'type_PAYMENT', 'type_TRANSFER']

for i in col:
    df[i] = df[i].astype(int)


df.head()

,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud,type_CASH_IN,type_CASH_OUT,type_DEBIT,type_PAYMENT,type_TRANSFER
0,129526.58,0.00,0.00,2103690.88,2233217.46,0.0,0,0,0,0,1
1,304210.97,6638620.67,6942831.64,513871.60,209660.63,0.0,1,0,0,0,0
2,57905.63,188.00,0.00,611506.02,669411.65,0.0,0,1,0,0,0
3,83102.70,2274365.81,2357468.51,122204.31,39101.61,0.0,1,0,0,0,0
4,14341.19,459181.00,444839.81,0.00,0.00,0.0,0,0,0,1,0

In [12]:
df.corr()

,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud,type_CASH_IN,type_CASH_OUT,type_DEBIT,type_PAYMENT,type_TRANSFER
amount,1.000000,0.616412,0.015986,-0.025032,0.287858,0.353824,-0.122710,0.051285,-0.027024,-0.199928,0.195895
oldbalanceOrg,0.616412,1.000000,0.792373,0.051553,0.198877,0.100941,0.319033,-0.104561,-0.021795,-0.166958,0.034992
newbalanceOrig,0.015986,0.792373,1.000000,0.108595,0.054770,-0.181319,0.530385,-0.181205,-0.009581,-0.077291,-0.101642
oldbalanceDest,-0.025032,0.051553,0.108595,1.000000,0.884940,-0.135278,0.113129,0.151203,0.034607,-0.154403,-0.120575
newbalanceDest,0.287858,0.198877,0.054770,0.884940,1.000000,-0.011221,0.030218,0.284597,0.020680,-0.199272,-0.170636
isFraud,0.353824,0.100941,-0.181319,-0.135278,-0.011221,1.000000,-0.349540,0.144954,-0.059690,-0.446578,0.456093
type_CASH_IN,-0.122710,0.319033,0.530385,0.113129,0.030218,-0.349540,1.000000,-0.304560,-0.020864,-0.156097,-0.223252
type_CASH_OUT,0.051285,-0.104561,-0.181205,0.151203,0.284597,0.144954,-0.304560,1.000000,-0.052009,-0.389112,-0.556514
type_DEBIT,-0.027024,-0.021795,-0.009581,0.034607,0.020680,-0.059690,-0.020864,-0.052009,1.000000,-0.026656,-0.038124
type_PAYMENT,-0.199928,-0.166958,-0.077291,-0.154403,-0.199272,-0.446578,-0.156097,-0.389112,-0.026656,1.000000,-0.285231
type_TRANSFER,0.195895,0.034992,-0.101642,-0.120575,-0.170636,0.456093,-0.223252,-0.556514,-0.038124,-0.285231,1.000000

In [14]:
df.isnull().sum()

amount            0
oldbalanceOrg     0
newbalanceOrig    0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
type_CASH_IN      0
type_CASH_OUT     0
type_DEBIT        0
type_PAYMENT      0
type_TRANSFER     0
dtype: int64

In [15]:
df = df.drop_duplicates()

df.duplicated().sum()

np.int64(0)

In [16]:
df['balance_diff_orig'] = df['oldbalanceOrg']-df['newbalanceOrig']
df['balance_diff_dest'] = df['oldbalanceDest']-df['newbalanceDest']
df

,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud,type_CASH_IN,type_CASH_OUT,type_DEBIT,type_PAYMENT,type_TRANSFER,balance_diff_orig,balance_diff_dest
0,129526.58,0.00,0.00,2103690.88,2233217.46,0.0,0,0,0,0,1,0.00,-129526.58
1,304210.97,6638620.67,6942831.64,513871.60,209660.63,0.0,1,0,0,0,0,-304210.97,304210.97
2,57905.63,188.00,0.00,611506.02,669411.65,0.0,0,1,0,0,0,188.00,-57905.63
3,83102.70,2274365.81,2357468.51,122204.31,39101.61,0.0,1,0,0,0,0,-83102.70,83102.70
4,14341.19,459181.00,444839.81,0.00,0.00,0.0,0,0,0,1,0,14341.19,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5065,82869.09,82869.09,0.00,104258.05,187127.14,1.0,0,1,0,0,0,82869.09,-82869.09
5066,9960382.40,9960382.40,0.00,0.00,0.00,1.0,0,0,0,0,1,9960382.40,0.00
5067,9960382.40,9960382.40,0.00,95048.58,10055430.98,1.0,0,1,0,0,0,9960382.40,-9960382.40
5068,1231309.64,1231309.64,0.00,0.00,0.00,1.0,0,0,0,0,1,1231309.64,0.00
5069,1231309.64,1231309.64,0.00,27650.97,1258960.61,1.0,0,1,0,0,0,1231309.64,-1231309.64

In [17]:
df['isFraud'].value_counts()

isFraud
0.0    2535
1.0    2529
Name: count, dtype: int64

In [18]:
from sklearn.preprocessing import StandardScaler

numeric_col = ['amount', 'oldbalanceOrg', 'newbalanceOrig', 'oldbalanceDest','newbalanceDest']

scaler = StandardScaler()

df[numeric_col] = scaler.fit_transform(df[numeric_col])

df.head()

,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud,type_CASH_IN,type_CASH_OUT,type_DEBIT,type_PAYMENT,type_TRANSFER,balance_diff_orig,balance_diff_dest
0,-0.374763,-0.405521,-0.211833,0.587678,0.415371,0.0,0,0,0,0,1,0.00,-129526.58
1,-0.263812,2.093358,3.035896,-0.117912,-0.364205,0.0,1,0,0,0,0,-304210.97,304210.97
2,-0.420254,-0.405450,-0.211833,-0.074580,-0.187086,0.0,0,1,0,0,0,188.00,-57905.63
3,-0.404249,0.450585,0.890948,-0.291741,-0.429913,0.0,1,0,0,0,0,-83102.70,83102.70
4,-0.447924,-0.232678,-0.003745,-0.345977,-0.444977,0.0,0,0,0,1,0,14341.19,0.00

In [19]:
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline



x = df.drop('isFraud',axis=1)
y = df['isFraud']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.33,random_state=42)

In [20]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier


models = {

    "LogisticRegression":{
        "model": LogisticRegression(),
        "params":{
            "C":[0.01,0.1,1,10],
            "max_iter":[1000]
        }
    },

    "KNN":{
        "model": KNeighborsClassifier(),
        "params":{
            "n_neighbors":[3,5,7,9],
            "weights":["uniform","distance"]
        }
    },

    "SVM":{
        "model": SVC(),
        "params":{
            "C":[0.1,1,10],
            "kernel":["linear","rbf"]
        }
    },

    "NaiveBayes":{
        "model": GaussianNB(),
        "params":{
            "var_smoothing":[1e-9,1e-8,1e-7]
        }
    },

    "DecisionTree":{
        "model": DecisionTreeClassifier(),
        "params":{
            "max_depth":[5,10,20,None],
            "criterion":["gini","entropy"]
        }
    },

    "RandomForest":{
        "model": RandomForestClassifier(),
        "params":{
            "n_estimators":[100,200],
            "max_depth":[10,20,None]
        }
    },

    "XGBoost":{
        "model": XGBClassifier(),
        "params":{
            "n_estimators":[100,200],
            "learning_rate":[0.01,0.1],
            "max_depth":[3,6]
        }
    }
}

In [ ]:
from sklearn.model_selection import GridSearchCV




res = []

for name,p in models.items():


    cv = GridSearchCV(p['model'],param_grid=p['params'],cv=5)

    cv.fit(x_train,y_train)
    
    res.append({
        "model":name,
        "cv-score":cv.best_score_,
        "param": cv.best_params_,
        "estimator": cv.best_estimator_
    })


res

In [1]:
import matplotlib.pyplot as plt

models = [i["model"] for i in res]
scores = [i["cv-score"] for i in res]

plt.figure(figsize=(8,5))

plt.bar(models, scores)

plt.xlabel("Models")
plt.ylabel("CV Score")
plt.title("Model Comparison (Cross Validation Score)")

plt.xticks(rotation=45) 

plt.show()

NameError: name 'res' is not defined

In [21]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

best_model = RandomForestClassifier(
    n_estimators = 100,
    max_depth = None,
    max_features ='sqrt',
    min_samples_split = 2,
    )

In [22]:
best_model.fit(x_train,y_train)

y_pred = best_model.predict(x_test)

accuracy = classification_report(y_test,y_pred)

print(accuracy)

              precision    recall  f1-score   support

         0.0       0.99      0.98      0.99       856
         1.0       0.98      0.99      0.99       816

    accuracy                           0.99      1672
   macro avg       0.99      0.99      0.99      1672
weighted avg       0.99      0.99      0.99      1672

In [23]:
from sklearn.model_selection import cross_val_score



scores = cross_val_score(best_model, x, y, cv=5)

print("Cross validation scores:", scores)
print("Mean CV score:", scores.mean())

Cross validation scores: [0.95064166 0.98914116 0.99308983 0.99210267 0.993083  ]
Mean CV score: 0.9836116649563579

In [24]:
import joblib as jb

jb.dump(best_model,"fraud_model.pkl")
jb.dump(scaler,"scaler.pkl")
jb.dump(x.columns,"features.pkl")

['features.pkl']